name: isl
channels:
        - anaconda
dependencies:
        - python=3.7
        - jupyter=1.0.0
        - numpy=1.15.4
        - pandas=0.23.4
        - seaborn=0.9.0
        - scikit-learn=0.20.1
        - python-graphviz=0.8.4
        - pip:
          - yellowbrick==0.9

